### ISSUE TITLE
Free functions lead to linker error

### ISSUE THREAD

**Issue by svn-kmf** [chazmcgarvey/vimcoder#11]
Hello,

at first, thank you for the Vimcoder plugin. I like it.

But now to the issue:
Sometimes I need **free functions** in my code (e.g. function objects) outside the solution class. This always leads to **linker errors (duplicate symbols)** when using 'make'.
I guess it arises from double compiling the code in the (`$CLASSNAME$.cc`) and linking it together.
The first compilation is the file itself. The second is by including the code by `#include "...cc"` in the `driver.cc`.
A workaround here is to set the free functions in an unknown namespace. But imho it would be better to adapt the Makefile to consider such techniques. I guess deleting the last explicit rule:

`driver$(EXEEXT): $CLASSNAME$.cc`

would do the job, but I'm not sure of any side effects or if there is a better solution.
What do you think?

Keep up the good work! :)

**Comment by svn-kmf** [comment]
Changed it in a fork. I'm new to GitHub and I'm not sure how to act now with my change recommendations. (Actually I'm not even sure, if the fork was the right method to provide changes/patches to your code :/.)

Anyhow you can see it under https://github.com/svn-kmf/vimcoder/commit/1194d5726146bbd525477f47dbedbd18914a46ab . 
May be it helps. If you have any tipps for me how to act next time. Please let me know :)

**Comment by chazmcgarvey** [comment]
I'm not completely sure I understand the problem, but can you take a look at c556717 and see if that is perhaps a simpler solution?

Thanks for the contribution; you're doing fine.

**Comment by svn-kmf** [comment]
Not only simpler, but also working. In my solution a change in `$(CLASSNAME).cc` didn't result in a rebuild of `driver.cc`.
For now your solution seems to be perfect. Now I can write code like this:

```c++
// code snippets of $(CLASSNAME).cc below

#include <algorithm>
...

// start of code resulting in linker error
struct A
{
  int length()
  {...}
  ...
};
bool comp(const A& a, const A& b)
{
  return a.length() < b.length();
}
// end of code resulting in linker error

struct SolutionClass
{
  int solutionFunction(...)
  {
    ...
    sort(vectorA.begin(), vectorB.begin(), comp);
    ...
  }
};
```
...without getting linker error for duplicate symbol of ```comp```. 

Do you know what I mean?

Anyhow I keep on testing during the SRMs and keep you informed about performance of the solution. Thank you for the solution for now!

**Comment by chazmcgarvey** [comment]
Okay, I'm glad it's working better for you.

I do now see what you mean. I did not know or remember the meaning of the term "free function," but I happened to guess correctly that they are just non-member functions. I need to review my C++ lingo!

**Comment by chazmcgarvey** [comment]
Thanks for reporting. Closing this since the fix for this has been applied.
