### ISSUE TITLE
Template isn't loaded when using `gnome-terminal -e vim --`

### ISSUE THREAD

**Issue by OneKorg** [chazmcgarvey/vimcoder#14]
using`gvim` and `xterm -e vim` works as expected

**Comment by OneKorg** [comment]
solved my problem using this article http://vim.wikia.com/wiki/Using_terminal_Vim_as_an_external_editor

**Comment by vishfrnds** [comment]
Having same problem solved by the given link above. Thanks
1) Create the file as given in link http://vim.wikia.com/wiki/Using_terminal_Vim_as_an_external_editor
2) In applet enter vim command: vim-gnome
