### ISSUE TITLE
Line separator in template is converted into CR+CR+LF (Windows)

### ISSUE THREAD

**Issue by sen-7** [chazmcgarvey/vimcoder#21]
Thanks for the great plugin. I use vimcoder with gvim (Version 8.0, Windows 10).

When I put any template file in the storage directory and start writing, line separators in the template are converted to CR+CR+LF.

The Util.readFile method seems to have trouble. The method adds line separators when combining the text (line 93). It also replace "\n" with a line separator when returning the combined text (line 101). So, when used in Windows, the 93rd line converts any line separator to CR+LF and then the 101st line converts (CR+)LF into (CR+)CR+LF.

I tried to delete the replaceAll method from the 101st line and it seems working properly. Please kindly check it.

**Comment by chazmcgarvey** [comment]
Good catch, thanks for reporting!
