### ISSUE TITLE
Last two lines of Comments are not correct syntax for Python

### ISSUE THREAD

**Issue by creasyw** [chazmcgarvey/vimcoder#9]
Hi Charles, Thanks for the excellent Vimcoder Editor. When I try to write the program in Python, the upload version always has two added lines of comments began with "\\\\", which is comment acceptable for C++ but not for Python. Where can I edit it? Thanks in advance!

**Comment by SiNBizkit** [comment]
I have the same problem.

**Comment by chazmcgarvey** [comment]
http://www.vim.org/scripts/script.php?script_id=3321
